### ISSUE TITLE
(node:366) UnhandledPromiseRejectionWarning: TypeError: client.broadcastEval is not a function

### ISSUE THREAD

**Issue by KainesLaw** [Gymnophoria/Arthur#33] opened 2021-06-17 20:45 UTC
I'm using your blacklist command, and when I try to blacklist my alt, in my console, it sends ```(node:366) UnhandledPromiseRejectionWarning: TypeError: client.broadcastEval is not a function```

My code is

```
module.exports = {
  name: "blacklist",
  run: async(client, message, args) => {
	if (!args[0]) return message.channel.send('I uh.. I need an ID');
	if (args[0] === message.author.id) return message.channel.send('no, bad');
	
	let user;
	try {
		user = await client.users.fetch(args[0]) || (await client.broadcastEval(`this.users.fetch('${args[0]}')`)).filter(item => !!item)[0];
	} catch (e) { 
		user = undefined;
	}
	
	let guild = client.guilds.cache.get(args[0]) || (await client.broadcastEval(`this.guilds.cache.get('${args[0]}')`)).filter(item => !!item)[0];
	
	if (!user && !guild) return message.channel.send('Could not find user or guild by that ID. rip');
	
	let deleteEntry = false;
	let result = await sql.get('SELECT * FROM hardBlacklist WHERE id = ?', [ args[0] ]);
	if (result) deleteEntry = true;
	
	if (user) {
		deleteEntry ? await sql.run('DELETE FROM hardBlacklist WHERE id = ?', [ args[0] ]) : await sql.run('INSERT INTO hardBlacklist (id, type) VALUES (?, ?)', [ args[0], 'user' ]);
		message.channel.send(deleteEntry ? `Removed \`${user.tag}\` from blacklist. But did they really learn their lesson?` : `Added \`${user.tag}\` to blacklist. *May they never bother you again*.`);
	}
	
	if (guild) {
		deleteEntry ? await sql.run('DELETE FROM hardBlacklist WHERE id = ?', [ args[0] ]) : await sql.run('INSERT INTO hardBlacklist (id, type) VALUES (?, ?)', [ args[0], 'guild' ]);
		message.channel.send(deleteEntry ? `Guild \`${guild.name}\` removed from blacklist. Anti-uf.` : `Guild \`${guild.name}\` added to blacklist. ***Uf***.`);
	}

	client.hardBlacklist = undefined;
}
};```

**Comment by dannyhpy** [comment] 2021-07-13 04:22
Hey @KainesLaw, it would be appreciated to have more information to reproduce your environment

Can you give me your...
- **Node.js** version
- **discord.js** version

It's more likely an issue with **discord.js** since they deprecated **_client.broadcastEval_**
Switching to **_client.shard.broadcastEval_** might fix the issue. Needs testing though!

**Comment by Gymnophoria** [comment] 2021-07-13 07:22
Weird, I didn't have email notifications on for repositories I watch, so my apologies for the delayed response. Anyways, this isn't an issue pertaining to Arthur itself, so I'm closing this.

That being said, Arthur is designed with sharding in mind, and broadcastEval is only available to bots that are sharded. To get this command in specific working on a bot that isn't set up for sharding, simply remove references to broadcastEval (so remove the parts of the guild and user lines including and past the || symbol).

If you need further help, feel free to join the support server - it's linked in the readme.

**Closed by Gymnophoria** 2021-07-13 07:22 UTC
